version: "3.9"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - app_network

  kafka:
    image: confluentinc/cp-kafka:7.4.1
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092 # Dành cho các container khác
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092 # Chấp nhận kết nối từ tất cả địa chỉ
      KAFKA_LISTENER_PORT: 9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    command:
      - sh
      - -c
      - |
        sleep 5;
        /etc/confluent/docker/run &
        # Tạo các topic cho các sự kiện
        kafka-topics --create --topic shipping-update-quantity --bootstrap-server kafka:9092 --replication-factor 1 --partitions 3;
        kafka-topics --create --topic shipping-create-shipment --bootstrap-server kafka:9092 --replication-factor 1 --partitions 3;
        kafka-topics --create --topic shipping-get-shipment-status --bootstrap-server kafka:9092 --replication-factor 1 --partitions 3;
        kafka-topics --create --topic inventory-update-quantity --bootstrap-server kafka:9092 --replication-factor 1 --partitions 3;
        kafka-topics --create --topic inventory-get-quantity --bootstrap-server kafka:9092 --replication-factor 1 --partitions 3;
        kafka-topics --create --topic inventory-inventory-alert --bootstrap-server kafka:9092 --replication-factor 1 --partitions 3;
        kafka-topics --list --bootstrap-server kafka:9092;
        wait
    networks:
      - app_network

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    environment:
      USER_SERVICE_URL: http://user:1111
      PRODUCT_SERVICE_URL: http://product:4444
      INVENTORY_SERVICE_URL: http://inventory:2222
      CART_SERVICE_URL: http://cart:4445
      ORDER_SERVICE_URL: http://order:3333
      PAYMENT_SERVICE_URL: http://payment:3334
      SHIPPING_SERVICE_URL: http://shipping:2223
      REVIEW_RATING_SERVICE_URL: http://reviewrating:5555
      NOTIFICATION_SERVICE_URL: http://notification:5556
      RECOMMENDATION_SERVICE_URL: http://recommendation:1112
    depends_on:
      - kafka
      - inventory
      - shipping
      - user
    ports:
      - "6868:6868"
    networks:
      - app_network

  shipping:
    build: ./shippingService
    container_name: shipping
    environment:
      POSTGRES_HOST: dpg-cu0tdmd2ng1s73e32250-a.singapore-postgres.render.com
      POSTGRES_PORT: 5432
      POSTGRES_USER: chpttgear_user
      POSTGRES_PASSWORD: cBUv879D8Rshnxy1eyog0HxePFqPPAXF
      POSTGRES_DB: chpttgear
      KAFKA_BROKER: kafka:9092
      SHIPPING_UPDATE_QUANTITY_TOPIC: shipping-update-quantity
      SHIPPING_CREATE_SHIPMENT_TOPIC: shipping-create-shipment
      SHIPPING_GET_SHIPMENT_STATUS_TOPIC: shipping-get-shipment-status
      PORT: 2223
      CLIENT_HOST: http://localhost:3000
      CLIENT_ID: shippingService
      GROUP_ID: shipping-group
    depends_on:
      - kafka
    ports:
      - "2223:2223"
    networks:
      - app_network

  inventory:
    build: ./inventoryService
    container_name: inventory
    environment:
      POSTGRES_HOST: dpg-cu0tdmd2ng1s73e32250-a.singapore-postgres.render.com
      POSTGRES_PORT: 5432
      POSTGRES_USER: chpttgear_user
      POSTGRES_PASSWORD: cBUv879D8Rshnxy1eyog0HxePFqPPAXF
      POSTGRES_DB: chpttgear
      KAFKA_BROKER: kafka:9092
      INVENTORY_UPDATE_QUANTITY_TOPIC: inventory-update-quantity
      INVENTORY_GET_QUANTITY_TOPIC: inventory-get-quantity
      INVENTORY_INVENTORY_ALERT_TOPIC: inventory-inventory-alert
      PORT: 2222
      CLIENT_HOST: http://localhost:3000
      CLIENT_ID: inventoryService
      GROUP_ID: inventory-group
    depends_on:
      - kafka
    ports:
      - "2222:2222"
    networks:
      - app_network

  user:
    build: ./userService
    container_name: user
    environment:
      DB_NAME: mixed_chptt_pxc
      DB_USER: sa
      DB_PASS: bvGGKK3v5JU7gKvIExEQdAW8n7GXcW0R
      DB_HOST: dpg-ctvo2n5ds78s73eomaig-a.singapore-postgres.render.com
      DB_PORT: 5432
      CLIENT_PORT: 3000
      PORT: 1111
      ACCESS_TOKEN_SECRET: chptt@20075851
    depends_on:
      - kafka
    ports:
      - "1111:1111"
    networks:
      - app_network

  order:
    build: ./orderService
    container_name: order
    environment:
      DB_NAME: mixed_chptt
      DB_USER: sa
      DB_PASS: SH8mzqwhcaSalLiI1mfhFldqpowgotZP
      DB_HOST: dpg-ctvnq9jtq21c73agid10-a.singapore-postgres.render.com
      DB_PORT: 5432
      PORT: 3333
      KAFKA_BROKER: kafka:9092
      ORDER_CREATE_TOPIC: order-create
      ORDER_UPDATE_STATUS_TOPIC: order-update-status
      ORDER_CANCEL_TOPIC: order-cancel
      CLIENT_HOST: http://localhost:3000
      CLIENT_ID: orderservice
      GROUP_ID: order-group
    depends_on:
      - kafka
    ports:
      - "3333:3333"
    networks:
      - app_network

payment:
  build: ./paymentService
  container_name: payment
  environment:
    DB_NAME: mixed_chptt
    DB_USER: sa
    DB_PASS: SH8mzqwhcaSalLiI1mfhFldqpowgotZP
    DB_HOST: dpg-ctvnq9jtq21c73agid10-a.singapore-postgres.render.com
    DB_PORT: 5432
    PORT: 3334
    KAFKA_BROKER: kafka:9092
    ORDER_CREATE_TOPIC: payment-create
    ORDER_UPDATE_STATUS_TOPIC: payment-update-status
    ORDER_CANCEL_TOPIC: payment-cancel
    CLIENT_HOST: http://localhost:3000
    CLIENT_ID: payment
    GROUP_ID: payment-group
  depends_on:
    - kafka
  ports:
    - "3334:3334"
  networks:
    - app_network
networks:
  app_network:
    driver: bridge
