version: "3.9"
services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_network
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - app_network
  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092 # Dành cho các container khác
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092 # Chấp nhận kết nối từ tất cả địa chỉ
      KAFKA_LISTENER_PORT: 9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    command:
      - sh
      - -c
      - |
        sleep 5;
        /etc/confluent/docker/run &
        # Tạo các topic cho các sự kiện
        kafka-topics --create --topic shipping-update-quantity --bootstrap-server kafka:9092 --replication-factor 1 --partitions 3;
        kafka-topics --create --topic shipping-create-shipment --bootstrap-server kafka:9092 --replication-factor 1 --partitions 3;
        kafka-topics --create --topic shipping-get-shipment-status --bootstrap-server kafka:9092 --replication-factor 1 --partitions 3;
        kafka-topics --create --topic inventory-update-quantity --bootstrap-server kafka:9092 --replication-factor 1 --partitions 3;
        kafka-topics --create --topic inventory-get-quantity --bootstrap-server kafka:9092 --replication-factor 1 --partitions 3;
        kafka-topics --create --topic inventory-inventory-alert --bootstrap-server kafka:9092 --replication-factor 1 --partitions 3;
        kafka-topics --list --bootstrap-server kafka:9092;
        wait
    networks:
      - app_network

  api-gateway:
    build:
      context: ./api-gateway # Thư mục chứa ứng dụng Java
      dockerfile: Dockerfile # Tệp Dockerfile
    container_name: api-gateway
    environment:
      USER_SERVICE_URL: https://user.qcapsule.io.vn
      PRODUCT_SERVICE_URL: http://product:4444
      INVENTORY_SERVICE_URL: https://inventory.qcapsule.io.vn
      CART_SERVICE_URL: http://cart:4445
      ORDER_SERVICE_URL: https://order.qcapsule.io.vn/
      PAYMENT_SERVICE_URL: https://payment.qcapsule.io.vn/
      SHIPPING_SERVICE_URL: https://shipping.qcapsule.io.vn
      REVIEW_RATING_SERVICE_URL: http://rating:5555
      RECOMMENDATION_SERVICE_URL: https://recommendation.qcapsule.io.vn
    depends_on:
      - kafka
      - product
      - cart
      - redis
      - rating
    ports:
      - "6868:6868"
    networks:
      - app_network

  product:
    build:
      context: ./productService # Thư mục chứa ứng dụng Java
      dockerfile: Dockerfile # Tệp Dockerfile
    container_name: product
    # depends_on:
    #   - kafka # Kafka cần chạy trước
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-d0g6lhadbo4c73b2puvg-a.singapore-postgres.render.com/mixed_chptt_9hfc
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: aEqWuuYGJnIqQgsX7cSuOSszIp8L03kD
      SPRING_APPLICATION_NAME: productService
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SERVER_PORT: 4444 # Đảm bảo rằng server chạy đúng cổng
    ports:
      - "4444:4444" # Mở cổng 4444
    networks:
      - app_network # Mạng tùy chỉnh để giao tiếp giữa các container

  cart:
    build:
      context: ./cartService # Thư mục chứa ứng dụng Java
      dockerfile: Dockerfile # Tệp Dockerfile
    container_name: cart
    # depends_on:
    #   - kafka # Kafka cần chạy trước
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-d0g6lhadbo4c73b2puvg-a.singapore-postgres.render.com/mixed_chptt_9hfc
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: aEqWuuYGJnIqQgsX7cSuOSszIp8L03kD
      SPRING_APPLICATION_NAME: cartService
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SERVER_PORT: 4445 # Đảm bảo rằng server chạy đúng cổng
    ports:
      - "4445:4445" # Mở cổng 4444
    networks:
      - app_network # Mạng tùy chỉnh để giao tiếp giữa các container

  rating:
    build:
      context: ./ratingService # Thư mục chứa ứng dụng Java
      dockerfile: Dockerfile # Tệp Dockerfile
    container_name: rating
    # depends_on:
    #   - kafka # Kafka cần chạy trước
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-d0g6lhadbo4c73b2puvg-a.singapore-postgres.render.com/mixed_chptt_9hfc
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: aEqWuuYGJnIqQgsX7cSuOSszIp8L03kD
      SPRING_APPLICATION_NAME: ratingService
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SERVER_PORT: 5555 # Đảm bảo rằng server chạy đúng cổng
    ports:
      - "5555:5555"
    networks:
      - app_network # Mạng tùy chỉnh để giao tiếp giữa các container

networks:
  app_network:
    driver: bridge
