spring.application.name=productService

server.port=4444
spring.datasource.url=jdbc:postgresql://dpg-cu0tdmd2ng1s73e32250-a.singapore-postgres.render.com:5432/chpttgear
spring.datasource.username=chpttgear_user
spring.datasource.password=cBUv879D8Rshnxy1eyog0HxePFqPPAXF
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.testWhileIdle=true
spring.datasource.validationQuery=SELECT 1
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
spring.jpa.properties.hibernate.default_schema=public 
spring.jpa.properties.hibernate.connection.isolation=READ_COMMITTED




