spring.application.name=productService

server.port=4444
spring.datasource.url=jdbc:postgresql://dpg-ctvo2n5ds78s73eomaig-a.singapore-postgres.render.com:5432/mixed_chptt_pxc
spring.datasource.username=sa
spring.datasource.password=bvGGKK3v5JU7gKvIExEQdAW8n7GXcW0R
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.testWhileIdle=true
spring.datasource.validationQuery=SELECT 1
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
spring.jpa.properties.hibernate.default_schema=public 
spring.jpa.properties.hibernate.connection.isolation=READ_COMMITTED

spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.pool-name=HikariCP-Pool
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000


