spring.application.name=notificationService

server.port=5555
spring.datasource.url=jdbc:postgresql://dpg-d0g6lhadbo4c73b2puvg-a.singapore-postgres.render.com/mixed_chptt_9hfc
spring.datasource.username=sa
spring.datasource.password=aEqWuuYGJnIqQgsX7cSuOSszIp8L03kD
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.testWhileIdle=true
spring.datasource.validationQuery=SELECT 1
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
spring.jpa.properties.hibernate.default_schema=public 
spring.jpa.properties.hibernate.connection.isolation=READ_COMMITTED
