const { fakerEN: faker } = require('@faker-js/faker')
const User = require('../models/user')
const Role = require('../models/role')
const Group = require('../models/group')
/**
 * Generate a random role ID.
 *
 * This function retrieves all roles from the database, extracts their IDs,
 * and returns a randomly selected role ID.
 *
 * @author Canh
 * @returns {Promise<number>} A promise that resolves to a random role ID.
 */
const generateRoleId = async () => {
  const roles = await Role.findAll()
  const roleIds = roles.map(role => role.id)

  const randomIndex = Math.floor(Math.random() * roleIds.length)
  const randomRoleId = roleIds[randomIndex]

  console.log(randomRoleId)
  return randomRoleId
}
/**
 * Generate a random group ID.
 *
 * This function retrieves all groups from the database, extracts their IDs,
 * and returns a randomly selected group ID.
 *
 * @author Canh
 * @returns {Promise<number>} A promise that resolves to a random group ID.
 */
const generateGroupId = async () => {
  const groups = await Group.findAll()
  const groupIds = groups.map(role => role.id)

  const randomIndex = Math.floor(Math.random() * groupIds.length)
  const randomRoleId = groupIds[randomIndex]

  console.log(randomRoleId)
  return randomRoleId
}
/**
 * Generate sample user data.
 *
 * This function generates an array of sample user data. Each user entry includes details such as
 * first name, last name, job description, email, gender, age, password, username, refresh token,
 * token expiration date, role ID, group ID, creation date, and update date.
 *
 * @author Canh
 * @returns {Promise<Array<Object>>} A promise that resolves to an array of user objects.
 */
const generateUsers = async () => {
  return await Promise.all(Array.from({ length: 10 }, async () => ({
    firstName: faker.person.firstName(),
    lastName: faker.person.lastName(),
    description: faker.person.jobDescriptor(),
    email: faker.internet.email(),
    gender: faker.helpers.arrayElement([-1, 0, 1, 2]),
    age: faker.number.int({ min: 18, max: 60 }),
    password: faker.internet.password(),
    username: faker.internet.userName(),
    refreshToken: faker.random.alphaNumeric(32),
    expiredToken: faker.date.future(),
    roleId: await generateRoleId(),
    groupId: await generateGroupId(),
    createdAt: faker.date.past(),
    updatedAt: faker.date.recent()
  })))
}

/**
 * Seed the users table with sample data.
 *
 * This function seeds the users table with sample data generated by the generateUsers function.
 * It first checks if the table is empty, and if so, it populates the table with the generated data.
 *
 * @author Canh
 * @returns {Promise<void>} A promise that resolves when the seeding is complete.
 */
const seedUsers = async () => {
  try {
    // Check if the users table is empty
    const count = await User.count()
    if (count === 0) {
      // If the table is empty, generate sample users data
      const users = await generateUsers()
      // Bulk create the sample data
      await User.bulkCreate(users, { validate: true })
    } else {
      // If the table is not empty, log a message
      console.log('Users table is not empty.')
    }
  } catch (error) {
    // Log any errors that occur during the seeding process
    console.log(`Failed to seed Users data: ${error}`)
  }
}

module.exports = seedUsers
