spring.application.name=cartService

server.port=4445
spring.datasource.url=jdbc:postgresql://dpg-cv3vqo9u0jms73ee72hg-a.singapore-postgres.render.com/chptt_gear_ot8g
spring.datasource.username=sa
spring.datasource.password=Gyb6QZCn9AqnbP8kLceq6du0fJGpOfeT
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.testWhileIdle=true
spring.datasource.validationQuery=SELECT 1
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
spring.jpa.properties.hibernate.default_schema=public 
spring.jpa.properties.hibernate.connection.isolation=READ_COMMITTED

spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.pool-name=HikariCP-Pool
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

endpoints.cors.allow-credentials=true
endpoints.cors.allowed-origins=*
endpoints.cors.allowed-methods=*
endpoints.cors.allowed-headers=*